language: python
python: "2.7"
sudo: false
services:
    - mysql
    - couchdb
cache:
    directories:
        - eggs
before_install:
    - mysql -uroot -e 'create database manoseimas;'
    - printf "[client]\ndatabase = manoseimas\nuser = root\npassword =\ndefault-character-set = utf8\n" > ~/.my.cnf
install:
    - python scripts/genconfig.py config/env/development.cfg
    - make
script:
    - make test
