language: python
python: "2.7"
sudo: false
services:
    - mysql
    - couchdb
cache:
    pip: true
    ccache: true
    directories:
        - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
before_install:
    - mysql -uroot -e 'create database manoseimas;'
    - printf "[client]\ndatabase = manoseimas\nuser = root\npassword =\ndefault-character-set = utf8\n" > ~/.my.cnf
install:
    - pip install -U pip
    - python scripts/genconfig.py config/env/development.cfg
    - make
script:
    - make test
