# -*- coding: utf-8 -*-
import unittest

from manoseimas.mps_v2.utils import is_state_actor


class TestStateActorHeuristics(unittest.TestCase):

    maxDiff = None

    example_state_actors = [
        u'Aplinkos apsaugos komitetas',
        u'Aplinkos ministerija',
        u'Audito komitetas',
        u'Baudžiamojo kodekso priežiūros komitetas',
        u'Biudžeto ir finansų komitetas',
        u'Ekonomikos komitetas',
        u'Energetikos ministerija',
        u'Europos reikalų komitetas',
        u'Europos teisės departamentas',
        u'Finansinių nusikaltimų tyrimo tarnyba prie Vidaus reikalų ministerijos',
        u'Finansų ministerija',
        u'Generalinės prokuratūros Organizuotų nusikaltimų ir korupcijos tyrimo departamento vyriausiasis prokuroras',
        u'Informacinės visuomenės plėtros komitetas prie Susisiekimo ministerijos',
        u'Kaimo reikalų komitetas',
        u'Komiteto išvadų rengėjas R. Šimašius',
        u'Komiteto pasiūlymas',
        u'Krašto apsaugos ministerija',
        u'Kultūros ministerija',
        u'Kultūros paveldo departamentas',
        u'Kūno kultūros ir sporto departamentas',
        u'Lietuvos Respublikos Konstitucinis Teismas',
        u'Lietuvos Respublikos Ministro Pirmininko tarnyba',
        u'Lietuvos Respublikos Prezidentas',
        u'Lietuvos Respublikos Prezidento kanceliarija',
        u'Lietuvos Respublikos Prezidentė',
        u'Lietuvos Respublikos Prezidentės dekretas',
        u'Lietuvos Respublikos Vyriausybė',
        u'Lietuvos Respublikos Vyriausybės kanceliarija',
        u'Lietuvos Respublikos generalinė prokuratūra',
        u'Lietuvos Respublikos konkurencijos taryba',
        u'Lietuvos Respublikos ryšių reguliavimo tarnyba',
        u'Lietuvos Respublikos specialiųjų tyrimų tarnyba',
        u'Lietuvos Respublikos trišalė taryba',
        u'Lietuvos Respublikos trišalės tarybos Kultūros komiteto pirmininkas P. Zurlys',
        u'Lietuvos Respublikos trišalės tarybos sekretoriatas',
        u'Lietuvos Respublikos vaiko teisių apsaugos kontrolieriaus įstaiga',
        u'Lietuvos Respublikos valstybinė kultūros paveldo komisija',
        u'Lietuvos Respublikos valstybės kontrolė',
        u'Lietuvos Respublikos valstybės saugumo departamentas',
        u'Lietuvos Respublikos vyriausioji rinkimų komisija',
        u'Lietuvos Respublikos ŽŪM Išteklių ir kokybės politikos departamentas',
        u'Lietuvos bioetikos komitetas',
        u'Lošimų priežiūros tarnyba prie Finansų ministerijos',
        u'Muitinės departamentas',
        u'Nacionalinio saugumo ir gynybos komitetas',
        u'Nacionalinė žemės tarnyba prie Žemės ūkio ministerijos',
        u'Narkotikų, tabako ir alkoholio kontrolės departamentas',
        u'Narkotikų, tabako ir alkoholio kontrolės departamentas (G. Belian)',
        u'Narkotikų, tabako ir alkoholio kontrolės departamentas A. Veryga',
        u'Policijos departamentas',
        u'Seimo kanceliarijos Teisės departamentas',
        u'Seimo kontrolierių įstaiga',
        u'Seimo nariai A. Dumbrava, B. Vėsaitė',
        u'Seimo nariai A. Matulas, V. Saulis, R. Žemaitaitis',
        u'Seimo nariai A. Palionis, V. Simulik, A. Mitrulevičius, V. Kamblevičius, O. Valiukevičiūtė, K. Starkevičius',
        u'Seimo nariai A. Paulauskas, D. Petrošius, A. Anušauskas',
        u'Seimo nariai A. Pitrėnienė, O. Leiputė, L. Dmitrijeva, G. Steponavičius, A. Zeltinis',
        u'Seimo nariai A. Skardžius, K. Daukšys, B. Vėsaitė',
        u'Seimo nariai A. Stancikienė, A. Dumčius, P. Gražulis, N. Puteikis, D. Teišerskytė, J. Narkevič',
        u'Seimo nariai A. Stancikienė, L. Balsys, A. Strelčiūnas, R. Baškienė, P. Gylys, P. Gražulis',
        u'Seimo nariai A. Stancikienė, L. Balsys, R. Baškienė P. Gražulis',
        u'Seimo nariai A. Stancikienė, P. Gylys, P. Gražulis',
        u'Seimo nariai A. Stancikienė, P. Gylys, V. Vasiliauskas',
        u'Seimo nariai A. Strelčiūnas, A. Mitrulevičius, V. V. Margevičienė',
        u'Seimo nariai A. Strelčiūnas, P. Gražulis',
        u'Seimo nariai B. Pauža, M. Bastys, A. Palionis, K. Starkevičius, G. Mikolaitis, A. Skardžius, V. Kamblevičius',
        u'Seimo nariai B. Pauža, V. Kamblevičius, J. Kondrotas, K. Starkevičius',
        u'Seimo nariai B. Vėsaitė ir K. Daukšys',
        u'Seimo nariai B. Vėsaitė, A. Mockus, G. PurvaneckienėV. Saulis, I. Šiaulienė, O. Leiputė, A. Dūdėnas, E. Šablinskas, A. Zeltinis, J. Požėla, D. Petrošius',
        u'Seimo nariai B. Vėsaitė, A. Skardžius',
        u'Seimo nariai B. Vėsaitė, B. Pauža, Orinta Leiputė',
        u'Seimo nariai D. Budrys, V. Bacevičius, V. Gapšys, J. Olekas, J. Sabatauskas E. Tamašauskas',
        u'Seimo nariai D. Kreivys ir K. Daukšys',
        u'Seimo nariai D. Mikutienė, A. Matulas',
        u'Seimo nariai D. Mikutienė, A. Matulas, A. Monkauskaitė, V. M. Čigriejienė, J. Požėla',
        u'Seimo nariai D. Teišerskytė, V. Juozapaitis',
        u'Seimo nariai E. Masiulis D. Teišerskytė K. Daukšys O. Valiukevičiūtė M. Pavilionienė A. Skardžius A. Patackas V. Stundys L. Dmitrijeva V. Juozapaitis E. Žakaris E. Gentvilas P. Gražulis A. Dumčius A. Stancikienė S. Dmitrijev A. Anušauskas',
        u'Seimo nariai G. Purvaneckienė ir A. Sysas',
        u'Seimo nariai J. Olekas, V. Gapšys, J. Sabatauskas',
        u'Seimo nariai J. Razma, V. Aleknaitė Abramikienė',
        u'Seimo nariai J. Vaickienė ir kt.',
        u'Seimo nariai K. Daukšys ir R. Paliukas',
        u'Seimo nariai K. Komskis, B. Bradauskas',
        u'Seimo nariai K. Miškinienė, A. Sysas',
        u'Seimo nariai L. Dmitrijeva V. V. Margevičienė R. Tamašiūnienė J. Vaickienė V. Filipovičienė G. Purvaneckienė J. Varkala R. Baškienė M. A. Pavilionienė A. Matulas',
        u'Seimo nariai L. Dmitrijeva ir kt.',
        u'Seimo nariai M. Petrauskienė, A. Mitrulevičius, A. Skardžius, B. Pauža, V. Saulis, B. Bradauskas',
        u'Seimo nariai P. Gylys, P. Gražulis, N. Puteikis, J. Vaickienė, J. Narkevič',
        u'Seimo nariai R. Baškienė, P. Urbšys, L. Balsys',
        u'Seimo nariai R. Šimašius D. Kuodytė',
        u'Seimo nariai R. Žemaitaitis, A. Skardžius, K. Daukšys',
        u'Seimo nariai R. Žemaitaitis, A. Skardžius, K. Daukšys, B. Vėsaitė, R. Žilinskas',
        u'Seimo nariai R. Žemaitaitis, K. Bartkevičius, A. Pitrėnienė',
        u'Seimo nariai V. Gapšys V. Skarbalius G. Tamošiūnas V. Filipovičienė V. Fiodorovas',
        u'Seimo nariai V. Gapšys, V. Bukauskas',
        u'Seimo nariai V. Juozapaitis V. Stundys',
        u'Seimo nariai V. Simulik, E. Žakaris',
        u'Seimo nariai V. Simulik, M. Zasčiurinskas, E. Žakaris',
        u'Seimo nariai V. Skarbalius, V. Gapšys,V. Filipovičienė',
        u'Seimo nariai V. Stundys, V. Juozapaitis, M. Adomėnas',
        u'Seimo nariai V. V. Margevičienė L. Kazlavickas',
        u'Seimo nariai: A. Dumčius J. Olekas',
        u'Seimo nariai: D. Budrys V. Bacevičius V. Gapšys J. Olekas J. Sabatauskas E. Tamašauskas',
        u'Seimo nariai: D. Budrys, V. Bacevičius, V. Gapšys, J. Olekas, J. Sabatauskas, E. Tamašauskas',
        u'Seimo nariai: D. Petrošius, A. Nesteckis, A. Palionis',
        u'Seimo nariai: G. Steponavičius D. Kreivys R. Šimašius V. Stundys V. Gapšys J. Požela',
        u'Seimo nariai: P. Gražulis, R. Žemaitaitis, K. Bartkevičius,V. Kamblevičius, A. Mazuronis, O. Valiukevičiūtė, J. Vaickienė, A. Dumbrava, K. Komskis',
        u'Seimo nariai: R. Baškienė A. Stancikienė, A. Patackas, P. Urbšys, N. Puteikis, V. Vasiliauskas',
        u'Seimo nariai: V. Gapšys V. Bukauskas S. Bucevičius D. Ulickas',
        u'Seimo nariai: V. Mazuronis, E. Žakaris, V. Simulik, J. Vaickienė, A. Mazuronis, K. Bartkevičius, V. Juozapaitis, P. Čimbaras',
        u'Seimo nario E. Šablinsko',
        u'Seimo narių V. Juozapaičio ir V. Stundžio',
        u'Seimo narys A. Anušauskas',
        u'Seimo narys A. Dumbrava',
        u'Seimo narys A. Mazuronis',
        u'Seimo narys A. Mitrulevičius',
        u'Seimo narys A. Palionis',
        u'Seimo narys A. Paulauskas',
        u'Seimo narys A. Salamakinas',
        u'Seimo narys A. Skardžius',
        u'Seimo narys A. Strelčiūnas',
        u'Seimo narys A. Sysas',
        u'Seimo narys B. Pauža',
        u'Seimo narys D. Kreivys',
        u'Seimo narys D. Petrulis',
        u'Seimo narys D. Ulickas',
        u'Seimo narys Dmitrijev Sergej',
        u'Seimo narys E. Masiulis',
        u'Seimo narys E. Šablinskas',
        u'Seimo narys E. Žakaris',
        u'Seimo narys J. Olekas',
        u'Seimo narys J. Požela',
        u'Seimo narys J. Razma',
        u'Seimo narys J. Sabatauskas',
        u'Seimo narys K. Bartkevičius',
        u'Seimo narys K. Grybauskas',
        u'Seimo narys K. Komskis',
        u'Seimo narys K. Kuzminskas',
        u'Seimo narys K. Starkevičius',
        u'Seimo narys L. Balsys',
        u'Seimo narys L. Talmont',
        u'Seimo narys M. Bastys',
        u'Seimo narys M. Zasčiurinskas',
        u'Seimo narys P. Gražulis',
        u'Seimo narys P. Saudargas',
        u'Seimo narys P. Čimbaras',
        u'Seimo narys R. J. Dagys',
        u'Seimo narys R. Šimašius',
        u'Seimo narys R. Žemaitaitis',
        u'Seimo narys S. Ursul',
        u'Seimo narys S. Šedbaras',
        u'Seimo narys Stankevičius Č. Vytautas',
        u'Seimo narys V. Bukauskas',
        u'Seimo narys V. Gapšys',
        u'Seimo narys V. Juozapaitis',
        u'Seimo narys V. Mazuronis',
        u'Seimo narys V. Stundys',
        u'Seimo narys Č. V. Stankevičius',
        u'Seimo narė A. Pitrėnienė',
        u'Seimo narė A. Stancikienė',
        u'Seimo narė B. Vėsaitė',
        u'Seimo narė D. Teišerskytė',
        u'Seimo narė G. Purvaneckienė',
        u'Seimo narė K. Miškinienė',
        u'Seimo narė M. A. Pavilionienė',
        u'Seimo narė M. Petrauskienė',
        u'Seimo narė R. Baškienė',
        u'Seimo narė R. Juknevičienė',
        u'Seimo narė R. Tamašunienė',
        u'Seimo narė V. Aleknaitė – Abramikienė',
        u'Seimo narė V. Filipovičienė',
        u'Seimo narė V. V. Margevičienė',
        u'Socialinių reikalų ir darbo komitetas',
        u'Socialinės apsaugos ir darbo ministerija',
        u'Susisiekimo ministerija',
        u'Sveikatos apsaugos ministerija',
        u'Sveikatos reikalų komitetas',
        u'Teisingumo ministerija',
        u'Teisės ir teisėtvarkos komitetas',
        u'Teisės ir teisėtvarkos komiteto biuro vedėja D. Latvelienė',
        u'Teisės ir teisėtvarkos komiteto patarėja D. Latvelienė',
        u'Teisės ir teisėtvarkos komiteto patarėja G. Morkūnienė',
        u'Teisės ir teisėtvarkos komiteto patarėja I. Leonavičiūtė',
        u'Teisės ir teisėtvarkos komiteto patarėja J. Janušauskienė',
        u'Teisės ir teisėtvarkos komiteto patarėja L. Zdanavičienė',
        u'Teisės ir teisėtvarkos komiteto patarėja M. Civilkienė',
        u'Teisės ir teisėtvarkos komiteto patarėja R. Karpavičiūtė',
        u'Teisės ir teisėtvarkos komiteto patarėja R. Varanauskienė',
        u'Teisės ir teisėtvarkos komiteto patarėjas V. Kanapinskas',
        u'Užsienio reikalų komitetas',
        u'Užsienio reikalų ministerija',
        u'Valstybinio socialinio draudimo fondo valdyba prie Socialinės apsaugos ir darbo ministerijos',
        u'Valstybinė akreditavimo sveikatos priežiūros veiklai tarnyba prie Sveikatos apsaugos ministerijos',
        u'Valstybinė duomenų apsaugos inspekcija',
        u'Valstybinė kainų ir energetikos kontrolės komisija',
        u'Valstybinė kelių transporto inspekcija prie Susisiekimo ministerijos',
        u'Valstybinė lietuvių kalbos komisija',
        u'Valstybinė ligonių kasa prie Sveikatos apsaugos ministerijos',
        u'Valstybinė maisto ir veterinarijos tarnyba',
        u'Valstybinė mokesčių inspekcija prie Finansų ministerijos',
        u'Valstybinė teismo medicinos tarnyba prie Teisingumo ministerijos',
        u'Valstybinė teritorijų planavimo ir statybos inspekcija prie Aplinkos ministerijos',
        u'Valstybinė vaistų kontrolės tarnyba prie Sveikatos apsaugos ministerijos',
        u'Valstybinė vartotojų teisių apsaugos tarnyba',
        u'Valstybės sienos apsaugos tarnyba prie Vidaus reikalų ministerijos',
        u'Valstybės vaiko teisių apsaugos ir įvaikinimo tarnyba prie Socialinės apsaugos ir darbo ministerijos',
        u'Valstybės valdymo ir savivaldybių komitetas',
        u'Valstybės valdymo ir savivaldybių komiteto biuro l.e.p vedėjas A. Astrauskas',
        u'Valstybės valdymo ir savivaldybių komiteto biuro vedėjas B. Kleponis, patarėja R. Mačiulytė',
        u'Valstybės valdymo ir savivaldybių komiteto patarėjas A. Astrauskas',
        u'Vidaus reikalų ministerija',
        u'Viešųjų pirkimų tarnyba',
        u'Vilniaus miesto savivaldybės administracijos Miesto ūkio ir transporto departamento Eismo organizavimo specialistai',
        u'Vilniaus miesto savivaldybės administracijos Saugaus miesto departamentas',
        u'Vyriausybės atstovo Panevėžio apskrityje tarnyba',
        u'Vyriausybės atstovo Vilniaus apskrityje tarnyba',
        u'Įmonių bankroto valdymo departamentas',
        u'Švietimo ir mokslo ministerija',
        u'Švietimo, mokslo ir kultūros komitetas',
        u'Ūkio ministerija',
        u'Žemės ūkio ministerija',
        u'Žmogaus teisių komitetas',

        u'A. Jusevičienė',
        u'A. Norkūnas',
        u'A. Vaičiulis',
        u'Alkoholizmo ir narkomanijos prevencijos komisija',
        u'Alytaus miesto savivaldybė',
        u'Alytaus regiono plėtros taryba',
        u'Antikorupcijos komisija',
        u'Biržų rajono apylinkės teismas',
        u'Biržų rajono savivaldybė',
        u'D. Komparskienė',
        u'Darbo grupė pasiūlymams dėl Europos Žmogaus Teisių Teismo Didžiosios kolegijos 2011 m. sausio 6 dienos sprendimo byloje Paksas prieš Lietuvą vykdymo parengti',
        u'Darbo grupė viešojo sektoriaus audito sistemai tobulinti',
        u'Energetikos komisija',
        u'Etninės kultūros globos taryba',
        u'Etninės kultūros globos tarybos pirmininkė D. Urbanavičienė',
        u'Europos Centrinis Bankas',
        u'Europos sisteminės rizikos valdyba',
        u'Generalinės prokuratūros prokuroras S. Verseckas',
        u'Gyventojų registro tarnyba',
        u'I. Bazylevas',
        u'Ignalinos atominės elektrinės regiono plėtros taryba',
        u'Ignalinos savivaldybė',
        u'J. Sykas, prokuroras',
        u'Jaunimo ir sporto reikalų komisija',
        u'Jonavos rajono savivaldybės administracija',
        u'Jungtinių Tautų vyriausiojo pabėgėlių komisaro regioninis Šiaurės Europos biuras',
        u'K. Daukšys, V. Stundys',
        u'Kaišiadorių rajono savivaldybė',
        u'Kalvarijos savivaldybė',
        u'Kauno m. mokyklos',
        u'Kauno miesto savivaldybė',
        u'Kauno miesto savivaldybės administracija',
        u'Kauno miesto savivaldybės administracijos Viešosios tvarkos skyrius',
        u'Kazlų Rūdos savivaldybės administracija',
        u'Klaipėdos apygardos teismas',
        u'Klaipėdos miesto savivaldybė Jūrinių ir vidaus vandenų reikalų komisija',
        u'Klaipėdos rajono savivaldybė',
        u'Konkurencijos taryba',
        u'Konstitucijos komisija',
        u'Kupiškio rajono meras',
        u'Lazdijų rajono savivaldybės administracija',
        u'Lietuvos Aukščiausiasis Teismas',
        u'Lietuvos apeliacinis teismas',
        u'Lietuvos bankas',
        u'Lietuvos banko priežiūros tarnyba',
        u'Lietuvos banko valdybos primininkas V. Vasiliauskas',
        u'Lietuvos gretutinių teisių asociacija „AGATA“',
        u'Lietuvos heraldikos komisija',
        u'Lietuvos kelių policijos tarnyba',
        u'Lietuvos kriminalinės policijos biuras',
        u'Lietuvos policijos tarnyba',
        u'Lietuvos vyriausiasis administracinis teismas',
        u'Lygių galimybių kontrolieriaus tarnyba',
        u'M. Bastys, Irena Šiaulienė, D. Teišerskytė, E. Žakaris, D. Petrošius',
        u'M. Zasčiurinskas',
        u'M. Zasčiurinskas, R. Markauskas, D. Ulickas, Z. Žvikienė, V. Vonžutaitė, R. Paliukas, G. Jakavonis J. Kondrotas, P. Narkevičius, P. Čimbaras, V. Skarbalius, V. Fiodorovas, K. Daukšys',
        u'Marijampolės regiono plėtros taryba',
        u'Marijampolės savivaldybė',
        u'Mažeikių rajono savivaldybė',
        u'Mažeikų rajono savivaldybės administracija',
        u'Molėtų rajono savivaldybė',
        u'Muitinės kriminalinė tarnyba',
        u'Nacionalinis M. K. Čiurlionio dailės muziejus',
        u'Nacionalinis transplantacijos biuras',
        u'Nacionalinis vėžio institutas',
        u'Nacionalinė sveikatos taryba',
        u'Nacionalinė teismų administracija',
        u'Nacionalinės sveikatos tarybos sekretoriatas',
        u'Neringos savivaldybė',
        u'Pakruojo rajono savivaldybė',
        u'Panevėžio miesto savivaldybė',
        u'Plungės rajono savivaldybės kultūros centro direktorius',
        u'Prienų rajono savivaldybės administracija',
        u'Raseinių rajono savivaldybė',
        u'Skuodo rajono savivaldybės administracijos Teisės, personalo ir dokumentų valdymo skyriaus vyriausioji specialistė Alina Beniušienė',
        u'Spaudos, radijo ir televizijos rėmimo fondas',
        u'Teikia Seimo nariai: R. Baškienė K. Kuzminskas R. Ačas Vida M. Čigriejienė P. Urbšys L. Balsys A. Dumbrava K. Bartkevičius V. Gailius D. Teišerskytė Z. Žvikienė J. K. R. Markauskas O. Valiukevičiūtė R. Tamašunienė V. Kravčionok',
        u'Teisėja Dumskienė Laima',
        u'Teisėjų garbės teismas',
        u'Teisėjų taryba',
        u'Trakų rajono savivaldybė',
        u'Užkrečiamųjų ligų ir AIDS centras',
        u'V. Stundys',
        u'Vida Jakiūnaitė',
        u'Vilniaus miesto savivaldybė',
        u'Vilniaus miesto savivaldybės administracija',
        u'Vyriausioji tarnybinės etikos komisija',
        u'VŠĮ Nacionalinis kraujo centras',
        u'VŠĮ Naujininkų poliklinika',
        u'VŠĮ Valstybinis patologijos centras',
        u'VŠĮ Vilniaus universiteto ligoninės Santariškių klinikos',
        u'VŠĮ Vilniaus universiteto ligoninės Žalgirio klinika',
        u'Šiaulių apygardos teismas',
        u'Šilalės rajono savivaldybė',
        u'Šilutės rajono savivaldybė',
        u'Širvintų rajono savivaldybė',
        u'Žagarės regioninio parko direkcija',
        u'Žemės ūkio rūmų taryba',
        u'„LATGA“',
    ]

    example_nonstate_actors = [
        u'Doc. Aurelijus Veryga, LRS Sveikatos reikalų komiteto neetatinis ekspertas',
        u'Komiteto neetatinė ekspertė A. Širinskienė',
        u'Komiteto neetatinė ekspertė D. Brogienė',
        u'Lietuvos verslo darbdavių konfederacijos Agro reikalų komitetas',
        u'Sveikatos reikalų komiteto neetatinis ekspertas D. Pūras',
        u'Sveikatos reikalų komiteto neetatinis ekspertas R. Stukas',
        u'Sveikatos reikalų komiteto neetatinis ekspertas doc. A. Veryga',
        u'Sveikatos reikalų komiteto neetatinis ekspertas doc. J. V. Vaitkevičius',
        u'Sveikatos reikalų komiteto neetatinis ekspertas prof. R. Stukas',
        u'Sveikatos reikalų komiteto neetatinis ekspertas prof. dr. R. Stukas',
        u'Sveikatos reikalų komiteto neetatinis ekspertas prof. habil. dr. A. Raslanas',
        u'Sveikatos reikalų komiteto neetatinė ekspertė A. Širinskienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė D. Brogienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė D. Jankauskienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė D. Zeleckienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė Doc. Dr. A. Širinskienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė G. Belian',
        u'Sveikatos reikalų komiteto neetatinė ekspertė J. Dičkutė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė J. Kulberkienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė N. Tarvydienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė Prof. dr. D. Jankauskienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė R. Kalėdienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė R. Lingienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė V. Žvirblienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė doc. dr. A. Širinskienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė dr. D. Brogienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė dr. D. Zagurskienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė dr. J. Dičkutė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė prof. D. Jankauskienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė prof. R. Kalėdienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė prof. habil. dr. R. Kalėdienė',
        u'Sveikatos reikalų komiteto neetatinė ekspertė, Mykolo Romerio universiteto Politikos ir vadybos fakulteto prodekanė, Politikos mokslų intituto profesorė dr. D. Jankauskienė',
        u'Valstybės įmonė „Registrų centras“',

        u'-',
        u'A. Budreckas',
        u'A. Drevinskas',
        u'A. Kulšė',
        u'A. Mitašiūnas',
        u'A. Raupys',
        u'A. S. Petniūnas',
        u'A. Silis',
        u'A. Veryga',
        u'AB „Achema“',
        u'AB „Amber grid“',
        u'AB „LOTOS Geonafta įmonių grupė“, UAB „Minijos nafta“, UAB „LL investicijos“',
        u'AB „Lesto“',
        u'AB „Lietuvos dujos“',
        u'AB „Litgrid“',
        u'AB „ORLEN Lietuva“',
        u'Advokatas G. Kaminskas',
        u'Advokatas R. Tilindis',
        u'Advokato Anatolijaus Novikovo kontora',
        u'Advokato padėjėjas M. Barkauskas',
        u'Advokatų kontora „VARUL“',
        u'Advokatų kontoros GLIMSTED atstovas J. Poderis (UAB Banginis atstovas)',
        u'Advokatų taryba',
        u'Akcinė bendrovė „Šiaulių energija“',
        u'Albertas Kučinskas',
        u'Almantas Lebednykas',
        u'Angelė Kostogrizienė Gausių šeimų asociacijos vadovė',
        u'Anoniminis',
        u'Antstolių rūmai',
        u'Aplinkosaugos koalicija',
        u'Apylinkių teismų teisėjų sąjunga',
        u'Architektė-urbanistė A. Selemonaitė',
        u'Asociacija Lietuvos kredito unijos',
        u'Asociacija „Apsaugos verslo grupė“',
        u'Asociacija „Infobalt“',
        u'Asociacija „Investuotojų forumas“',
        u'Asociacija „Kultūros savivaldos kolegija“, Lietuvos viešųjų bibliotekų asociacijų',
        u'Asociacija „Lažybų organizatorių aljansas“',
        u'Asociacija „Lietuvos antstolių rūmai“',
        u'Asociacija „Lietuvos maisto pramonė“',
        u'Asociacija „Lietuvos maisto pramonė“, Lietuvos grūdų perdirbėjų asociacija, Lietuvos mėsos perdirbėjų asociacija, Lietuvos paukštininkystės asociacija',
        u'Asociacija „Lietuvos neįgaliųjų forumas“',
        u'Asociacija „Metro sąjūdis“',
        u'Asociacija „Šnieriškių bendruomenė“',
        u'Asociacijos „Šnieriškių bendruomenė“ pirmininkas Sergejus Jeriomenko',
        u'Baltijos pluoštinių kultūrų augintojų ir perdirbėjų asociacija',
        u'Bart Pauwels, Ernesta Pauvels',
        u'Biodegalų asociacija',
        u'Brigita Kymantaitė Lietuvos gyvūnų teisių apsaugos organizacijos vadovė',
        u'Bronislava Daunorienė',
        u'Buhalterių asociacijų aljansas',
        u'D. Augutienė, L. Jokubauskienė, ir kt.',
        u'D. Stumbrienė (193 parašai)',
        u'D. Urbonas',
        u'D. Čibirienė',
        u'Darbo saugos specialistų darbdavių asociacija',
        u'Didžiųjų miestų merų forumas',
        u'Doc. Dr. M. Ališauskienė, Vytauto didžiojo universiteto Socialinių mokslų fakulteto Sociologijos katedros vedėja; Tarptautinės naujųjų religijų studijų asociacijos viceprezidentė',
        u'Doc. dr. G. Kalčinskas',
        u'Durpių įmonių asociacija „Lietuviškos durpės“ Ruošė: Ginutis Juozapavičius',
        u'E. Rimgaila ir 1180 piliečių parašų',
        u'Eglė Kybartienė Lietuvos vartotojų organizacijų aljanso prezidentė',
        u'Eksploatuoti netinkamų transporto priemonių tvarkytojų asociacija',
        u'Elektronikos platintojų asociacija',
        u'Europos žmogaus teisių fondas',
        u'G. Belian',
        u'G. Grigas',
        u'Gamtos apsaugos asociacija „Baltijos vilkas“',
        u'Gamtos apsaugos asociacija „Baltijos vilkas“ su 8212 piliečių parašais',
        u'Gausių šeimų asociacija',
        u'Geologijos įmonių asociacija',
        u'Geros Valios Fondas',
        u'Gidų ir kelionės vadovų profesinė sąjunga „Solidarumas“',
        u'Giedrius',
        u'Ginčuose dalyvaujančių buhalterių asociacija',
        u'Gretutinių teisių asociacija “GRETA“',
        u'Ikiteisminio tyrimo įstaigų profesinė sąjunga',
        u'Investicijų forumas',
        u'Investuotojų asociacija',
        u'Izraelio – Lietuvos draugystės asociacija',
        u'J. Vaitkus',
        u'J. Vaiškūnas',
        u'K. Klimas',
        u'K. Petrauskas',
        u'K. Rimkus, ūkininkas',
        u'K. Turčinavičius',
        u'KTU Architektūros ir statybos instituto Teritorijų planavimo centras dr. E. Ramanauskas, dr. L. Dringelis',
        u'Kauno J. Urbšio katalikiškos vid. Mklos direktorius P. Martinaitis',
        u'Kauno susivienijimas „Sodai“',
        u'Kauno technologijos universiteto prorektorius P. Žiliukas',
        u'Kauno žydų religinė bendruomenė',
        u'Kiaulių augintojų asociacija',
        u'Klaipėdos laisvoji ekonominė zona',
        u'Klaipėdos universiteto Humanitarinių mokslų fakultetas',
        u'Koalicija „Moters teisės-visuotinės žmogaus teisės“',
        u'Kooperatinė bendrovė „Lietuvos kooperatyvų sąjunga“',
        u'Kristina M.',
        u'L. Gudauskienė',
        u'L. Naudužas',
        u'LGL (nacionalinė lesbiečių, gėjų, biseksualių ir transseksualių teisių organizacija)',
        u'LITDEA , nevyriausybinių organizacijų skėtinė organizacija, asociacija',
        u'Lauko reklamos asociacija',
        u'Legalaus verslo aljansas',
        u'Lietuvių kalbos gynėjų sąjungos Ekspertų tarybos narys Prof. V. Labutis',
        u'Lietuvių kalbos instituto darbuotojos: dr. O. Aleknavičienė, prof. dr. L. Kalėdienė',
        u'Lietuvos Aludarių Gildija, Alaus, Sidro ir Nealkoholinių Gėrimų Importuotojų Asociacija, Pakartotinio Naudojimo Gėrimų Pakuočių Naudotojų Asociacija',
        u'Lietuvos Huntingtono ligos asociacija',
        u'Lietuvos Persitvarkymo Sąjūdžio iniciatyvinės grupės klubas',
        u'Lietuvos Raudonojo Kryžiaus draugija',
        u'Lietuvos Respublikos namų ir žemės sklypų savininkų sąjunga',
        u'Lietuvos Respublikos transporto priemonių draudikų biuras',
        u'Lietuvos Respublikos žemės ūkio rūmai',
        u'Lietuvos Sąjūdis',
        u'Lietuvos Sąjūdžio Vilniaus miesto taryba',
        u'Lietuvos Sąjūdžio Vilniaus skyriaus taryba',
        u'Lietuvos Sąjūdžio Vilniaus skyrius',
        u'Lietuvos advokatūra',
        u'Lietuvos agrarinės ekonomikos institutas',
        u'Lietuvos aludarių gildija',
        u'Lietuvos anesteziologųreanimatologų draugija',
        u'Lietuvos antstolių rūmai',
        u'Lietuvos apskaitos įmonių asociacija',
        u'Lietuvos architektų rūmai J. Vaškevičius',
        u'Lietuvos asociacija „Gyvastis“',
        u'Lietuvos atsinaujinančių išteklių energetikos konfederacija',
        u'Lietuvos auditorių rūmai',
        u'Lietuvos autoverslininkų asociacija',
        u'Lietuvos autoverslininkų asociacija (R. Knyva generalinis direktorius Lietuvos autoverslininkų asociacija)',
        u'Lietuvos bankų asociacija',
        u'Lietuvos bankų klientų asociacija',
        u'Lietuvos blaivybės fondas',
        u'Lietuvos centrinė kredito unija',
        u'Lietuvos centrinė kredito unija ir Asociacija Lietuvos kredito unijos',
        u'Lietuvos daržovių augintojų asociacija',
        u'Lietuvos dermatovenerologų draugija',
        u'Lietuvos draudikų asociacija',
        u'Lietuvos dujų asociacija',
        u'Lietuvos dviratininkų bendrijos pirmininkas L. Vainius, Lietuvos dviračių verslo asociacijos prezidentas A. Paulikaitis, sporto klubą „Vilimeksas“ atstovaujantis G. Adamonis ir kt.',
        u'Lietuvos dviratininkų draugija',
        u'Lietuvos edukologijos universiteto Istorijos fakultetas',
        u'Lietuvos edukologijos universiteto Istorijos fakulteto dekanas E. Jovaiša',
        u'Lietuvos farmacijos darbuotojų profesinė sąjunga',
        u'Lietuvos farmacijos sąjunga',
        u'Lietuvos farmacijos sąjungos prezidentas, Tarptautinės farmacijos federacijos (FIP) tikrasis narys, Lietuvos sveikatos mokslų universiteto Vaistų chemijos katedros profesorius E. Tarasevičius',
        u'Lietuvos geografų draugija',
        u'Lietuvos gidų sąjunga, Lietuvos gidų gildija, Gidų ir kelionės vadovų profesinė sąjunga „Solidarumas“, Lietuvos turizmo rūmai',
        u'Lietuvos grūdų perdirbėjų asociacija',
        u'Lietuvos gydytojų sąjunga',
        u'Lietuvos gydytojų vadovų sąjunga',
        u'Lietuvos gyventojų genocido ir rezistencijos tyrimo, aukų rėmimo ir atminimo įamžinimo fondas',
        u'Lietuvos gyvybės draudimo įmonių asociacija',
        u'Lietuvos gyvūnų teisių apsaugos organizacijos vadovė Brigita Kymantaitė Lietuvos kinologų draugijos prezidentė Ramunė Kazlauskaitė',
        u'Lietuvos istorijos institutas',
        u'Lietuvos istorijos instituto direktorius R. Miknys',
        u'Lietuvos istorinių transporto priemonių išsaugojimo asociacija „Retromobile“',
        u'Lietuvos jungtinio demokratinio judėjimo konfederacija',
        u'Lietuvos jūrininkų asociacija (P. Bekėža)',
        u'Lietuvos jūrininkų sąjunga',
        u'Lietuvos kabelinės televizijos asociacija',
        u'Lietuvos kaimo bendruomenių sąjunga',
        u'Lietuvos kariuomenės kūrėjų savanorių sąjungos Kauno kūrėjų sąjunga ir kiti',
        u'Lietuvos karjerų asociacija',
        u'Lietuvos kinologų draugija',
        u'Lietuvos kompiuterininkų sąjunga',
        u'Lietuvos kompozitorių sąjunga',
        u'Lietuvos kreditas (kredito unijų asociacija)',
        u'Lietuvos krepšinio federacija',
        u'Lietuvos laisvosios rinkos institutas',
        u'Lietuvos laisvės kovos sąjūdis',
        u'Lietuvos laivų savininkų asociacija',
        u'Lietuvos laivų savininkų asociacija (V. Lygnugaris)',
        u'Lietuvos leidėjų asociacija',
        u'Lietuvos leidėjų asociacija, Lietuvos bibliotekininkų draugija, Lietuvos rašytojų sąjunga',
        u'Lietuvos ligoninių asociacija',
        u'Lietuvos lošimo operatorių asociacija',
        u'Lietuvos lošimų asociacijos operatorių prezidentas S. Petravičius, Nacionalinės lošimų ir žaidimų verslo asociacijos valdybos pirmininkas S. Kacas, Lažybų organizatorių aljanso valdybos pirmininkas G. Staniulis',
        u'Lietuvos maisto pramonininkų konfederacija',
        u'Lietuvos matininkų asociacija',
        u'Lietuvos medicinos studentų asociacija',
        u'Lietuvos medžiotojų ir žvejų draugija',
        u'Lietuvos medžiotojų sąjunga „Gamta“',
        u'Lietuvos meno kūrėjų asociacija',
        u'Lietuvos miško ir miško pramonės darbuotojų profesinių sąjungų federacija',
        u'Lietuvos miško savininkų asociacija',
        u'Lietuvos mokslo tarybos pirmininkas E. Butkus',
        u'Lietuvos mokslų akademija',
        u'Lietuvos mokslų akademijos narių vardu LMA prezidiumo narys Humanitarinių ir socialinių mokslų skyriaus pirmininkas prof. Aleksandras Vasiliauskas',
        u'Lietuvos mokytojų profesinė sąjunga',
        u'Lietuvos muziejų asociacija',
        u'Lietuvos mėsos perdirbėjų asociacija',
        u'Lietuvos nacionalinio radijo ir televizijos taryba',
        u'Lietuvos nacionalinis radijas ir televizija',
        u'Lietuvos nacionalinė vartotojų federacija',
        u'Lietuvos nacionalinė vežėjų automobiliais asociacija „Linava“',
        u'Lietuvos nacionalinės sveikatos tarybos pirmininkas J. Pundzius',
        u'Lietuvos naujoji apaštalų bažnyčia',
        u'Lietuvos nealkoholinių gėrimų gamintojų bei importuotojų asociacija',
        u'Lietuvos nepriklausomybės akto signataras Zigmas Vaišvila',
        u'Lietuvos nepriklausomybės akto signatarų klubas',
        u'Lietuvos nepriklausomybės aktų signatarų klubo prezidentė B. Valionytė',
        u'Lietuvos neįgaliųjų forumas',
        u'Lietuvos notarų rūmai',
        u'Lietuvos pacientų forumas',
        u'Lietuvos pacientų organizacijų atstovų taryba',
        u'Lietuvos pacientų organizacijų atstovų taryba, Lietuvos gydytojų vadovų sąjunga, Lietuvos gydytojų sąjunga, Lietuvos sveikatos apsaugos darbuotojų profesinė sąjunga, Lietuvos laisvosios rinkos institutas',
        u'Lietuvos pieno ūkių asociacija',
        u'Lietuvos politinių kalinių ir tremtinių sąjunga',
        u'Lietuvos pramonininkų konfederacija',
        u'Lietuvos pramonininkų konfederacija, Lietuvos prekybos pramonės ir amatų rūmų asociacija, Lietuvos autoverslininkų asociacija',
        u'Lietuvos prekybos įmonių asociacija',
        u'Lietuvos prekybos, pramonės ir amatų rūmų asociacija',
        u'Lietuvos privačių geležinkelių įmonių asociacija',
        u'Lietuvos privačių sveikatos priežiūros įstaigų asociacija',
        u'Lietuvos profesinių sąjungų federacija „Sandrauga“',
        u'Lietuvos profesinių sąjungų konfederacija',
        u'Lietuvos profesinė sąjunga „Solidarumas“',
        u'Lietuvos profesinės saugos lyga',
        u'Lietuvos projektavimo įmonių asociacija, Lietuvos statybos inžinierių sąjunga',
        u'Lietuvos psichologų sąjunga',
        u'Lietuvos radijo ir televizijos asociacija',
        u'Lietuvos radijo ir televizijos komisija',
        u'Lietuvos rajoninių ligoninių asociacija',
        u'Lietuvos rašytojų sąjungos nariai, Vydas Astas',
        u'Lietuvos regionų kultūros bendruomenė',
        u'Lietuvos reklamos biuras',
        u'Lietuvos respublikiniai būsto valdymo ir priežiūros rūmai',
        u'Lietuvos savivaldybių asociacija',
        u'Lietuvos savivaldybių asociacijos taryba',
        u'Lietuvos savivaldybių asociacijos valdyba',
        u'Lietuvos savivaldybių seniūnų asociacija',
        u'Lietuvos slaugos specialistų organizacija',
        u'Lietuvos smulkiojo ir vidutinio verslo taryba',
        u'Lietuvos smulkiųjų vartojimo kreditų asociacija',
        u'Lietuvos sodininkų bendrijų asociacija',
        u'Lietuvos sodininkų draugija',
        u'Lietuvos sodininkų draugija Kauno susivienijimas „Sodai“',
        u'Lietuvos sporto federacijų sąjunga',
        u'Lietuvos sporto universitetas',
        u'Lietuvos statybininkų asociacija',
        u'Lietuvos studentų sąjunga',
        u'Lietuvos studentų sąjungos prezidentas P. Baltokas',
        u'Lietuvos sutrikusio intelekto žmonių globos bendrija „Viltis“',
        u'Lietuvos sveikatingumo klubų asociacija',
        u'Lietuvos sveikatos mokslų universitetas',
        u'Lietuvos sveikatos mokslų universitetas. Gyvulininkystės institutas',
        u'Lietuvos sveikatos mokslų universiteto Medicinos akademijos Visuomenės sveikatos fakultetas',
        u'Lietuvos sveikatos mokslų universiteto ligoninė Kauno klinikos',
        u'Lietuvos sveikuolių sąjunga',
        u'Lietuvos tautinis olimpinis komitetas',
        u'Lietuvos techninės apžiūros įmonių asociacija „Transeksta“',
        u'Lietuvos teisininkų draugija',
        u'Lietuvos teisės institutas',
        u'Lietuvos teisėsaugos pareigūnų federacija',
        u'Lietuvos turizmo asociacija',
        u'Lietuvos tėvų forumas',
        u'Lietuvos tėvų forumo pirmininkas A. Murauskas',
        u'Lietuvos universitetų rektorių konferencijos prezidentas P. Baršauskas',
        u'Lietuvos vaikų nefrologų draugija',
        u'Lietuvos vaistininkų sąjunga',
        u'Lietuvos vaistinių asociacija',
        u'Lietuvos vandens tiekėjų asociacija',
        u'Lietuvos vartojimo lizingo ir kredito asociacija',
        u'Lietuvos verslinių sodų asociacija „Vaisiai ir uogos“',
        u'Lietuvos verslo darbdavių konfederacija',
        u'Lietuvos verslo konfederacija',
        u'Lietuvos verslo konfederacija, Lietuvos žemės ūkio bendrovių asociacija, Lietuvos verslo darbdavių konfederacija, Asociacija Investors’ Forum',
        u'Lietuvos verslo žurnalistų klubas',
        u'Lietuvos vidaus reikalų sistemos respublikinė profesinė sąjunga',
        u'Lietuvos viešbučių ir restoranų asociacija',
        u'Lietuvos visuomenės sveikatos asociacija',
        u'Lietuvos vyskupų konferencija',
        u'Lietuvos vėjo elektrinių asociacija',
        u'Lietuvos šilumos tiekėjų asociacija',
        u'Lietuvos švietimo darbuotojų profesinė sąjunga',
        u'Lietuvos ūkininkų sąjunga',
        u'Lietuvos ūkininkų sąjunga ir Baltijos pluoštinių kultūrų augintojų ir perdirbėjų asociacija',
        u'Lietuvos žemės savininkų sąjunga',
        u'Lietuvos žemės savininkų sąjungos Šiaulių skyrius',
        u'Lietuvos žemės ūkio bendrovių asociacija',
        u'Lietuvos žemėtvarkos ir hidrotechnikos inžinierių sąjunga',
        u'Lietuvos žmogaus teisių asociacija',
        u'Lietuvos žmogaus teisių gynimo asociacija',
        u'Lietuvos žmogaus teisių koordinavimo centras',
        u'Lietuvos žuvininkystės produktų gamintojų asociacijos pirmininkas A. Bargaila (LŽPGA)',
        u'Lietuvos žuvininkystės produktų gamintojų asociacijos pirmininkas A. Bargaila ; Klaipėdos žuvininkystės įmonių asociacijos „Jūros žvejys“ pirmininkas A. Maželis Tarptautinės žuvies perdirbėjų ir Žvejų asociacijos „Baltijos vienybė“ Pirmininkas Pranas Norvilas',
        u'Lietuvos žuvininkystės produktų gamintojų asociacijos pirmininkas A. Bargaila Klaipėdos žuvininkystės įmonių asociacijos „Jūros žvejys“ pirmininkas A. Maželis',
        u'Lietuvos žuvininkystės produktų gamintojų asociacijos pirmininkas A. Bargaila; Klaipėdos žuvininkystės įmonių asociacijos „Jūros žvejys“ pirmininkas A. Maželis',
        u'Local American Working Group (LAWG)',
        u'M. Gaigalas',
        u'M. Komiago',
        u'M. Lukas',
        u'M. Vantens',
        u'Maisto papildų gamintojų asociacija',
        u'Mažųjų alaus daryklų asociacija',
        u'Medienos prekybos asociacija',
        u'Mikas Petrauskas UAB Kauno detektyvų agentūros direktorius',
        u'Miško savininkų asociacijos valdybos pirmininkas A. Gaižutis',
        u'Mokslo ir enciklopedijų leidybos centras',
        u'Monrealio lietuviškos radijo laidos programos vedėjas L. Stankevičius',
        u'Muzikos autorių teisių asociacija „NATA“',
        u'Mykolo Romerio universitetas',
        u'Mykolo Romerio universiteto Politikos ir vadybos fakultetas',
        u'Mykolo Romerio universiteto Teisės fakultetas',
        u'Mykolo Romerio universiteto Teisės fakulteto Administracinės teisės ir proceso katedros vedėjas prof.dr. A. Urmonas',
        u'Mėgėjų žvejybos tarybos (MŽT) pirmininkas A. Kontautas',
        u'N. Jaseliūnienė, V. Lukošius',
        u'NVO Teisės institutas',
        u'Nacionalinis pareigūnų profesinių sąjungų susivienijimas',
        u'Nacionalinė antikorupcijos asociacija',
        u'Nacionalinė donorų asociacija',
        u'Nacionalinė lošimų ir žaidimų verslo asociacija',
        u'Nacionalinė nevyriausybinių vystomojo bendradarbiavimo organizacijų platforma',
        u'Nacionalinė pastatų administratorių asociacija',
        u'Nacionalinė sveikatos priežiūros įstaigų asociacija',
        u'Nacionalinė tabako ir alkoholio kontrolės koalicija',
        u'Nacionalinė turizmo verslo asociacija',
        u'Nacionalinė vaistų prekybos asociacija',
        u'Nacionalinės premijos laureatai',
        u'Nepriklausomų prodiuserių asociacija',
        u'Nevyriausybinių organizacijų informacijos ir paramos centras',
        u'Nevyriausybinių organizacijų koordinacinė taryba LR Konstitucijai ginti',
        u'Nevyriausybinių organizacijų kreipimasis (10)',
        u'Nevyriausybinių organizacijų kreipimasis (7)',
        u'O. Batkienė',
        u'Odontologų rūmai',
        u'Olegas Rimanas',
        u'Olegas Rimanas ( Įgaliotasis asmuo pagal 2012 m. vasario mėn. 22 d. Jungtinės veiklos sutartį Nr. 1 UAB „Privačių detektyvų biuras“ Direktorius )',
        u'Onkobematologinių ligonių bendrija „Kraujas“',
        u'Onkohematologinių ligonių bendrija „Kraujas“ Asociacija „Gyvastis“, Lietuvos išsėtinės sklerozės sąjunga ; Lietuvos vaikų vėžio asociacija „Paguoda“ Asociacija „Pozityvus gyvenimas“, Lietuvos artrito asociacija, Stomuotų žmonių asociacija „Diena“, Kauno bendrija „Likimas“, VŠĮ Tėviškės namai, Onkologinėmis ligomis sergančių moterų draugija „Eivena“, VŠĮ „Kartu lengviau“ (sergantieji smegenų navikais), Huntingtono ligos asociacija, Lietuvos sergančiųjų genetinėmis nervųraumenų ligomis asociacija „Sraunija“, ŽIV ir AIDS paveiktų moterų bei jų artimųjų asociacija „Demetra“, Vaiko širdies asociacija, Panevėžio moterų sergančių krūties ligomis bendrija, „Atgaja“, Lietuvos sergančiųjų prostatos vėžiu asociacija, Lietuvos Alzheimerio ligos asociacija, Šilutės rajono sergančių onkologinėmis ligomis draugija „Vivafemina“, Lietuvos pacientų forumas, Bechterevo liga sergančių draugija „Judesys“, Lietuvos diabeto sąjunga, Šiaulių apskrities sergančiųjų epilepsija ir jų globėjų draugija, Elektrėnų seniūnijos sveikatos draugija „Mes esame“',
        u'Padangų importuotojų organizacija',
        u'Pagalbos onkologiniams ligoniams asociacija',
        u'Panevėžio verslininkų asociacija (toliau -PVA)',
        u'Panevėžio vyskupija, Utenos dekanatas, Užpalių parapija',
        u'Pasipriešinimo okupaciniams režimams dalyvių ir nuo okupacijų nukentėjusių asmenų teisių ir reikalų komisija',
        u'Personalo valdymo profesionalų asociacija',
        u'Pil. R. Ščerbavičius',
        u'Pilietis A. Bačkaitis',
        u'Pilietis Gediminas',
        u'Pilietis H. Grochovskis',
        u'Pilietis H. Žukauskas',
        u'Pilietis L. Jakučionis',
        u'Pilietis V. Alenskas',
        u'Pilietis V. Lukminas',
        u'Pilietė A. Butkutė-Žverelo',
        u'Piliečiai G. A. Kalėda, S. S. Jocas, Zarasų rajono Žemdirbių asociacija',
        u'Prekybos įmonių asociacija',
        u'Privačių medžioklės plotų savininkų asociacija',
        u'Prof. A. Kirkutis, Lietuvos sveikos gyvensenos ir natūraliosios medicinos rūmų Prezidentas',
        u'Prof. G. Navaitis',
        u'Prof. dr. S. Arlauskas, MRU',
        u'Profesinė sąjunga „Uostininkas“',
        u'Prokurorų profesinė sąjunga',
        u'R. Baliukevičienė ir kt.',
        u'R. Jocienė ir kt.',
        u'R. Klimas – Visuomenės kraštotvarkos draugijos valdybos narys, buvęs miškų ūkio ministras',
        u'R. Marijona Bliznikienė',
        u'R. Skrinskas',
        u'R. Stankauskas',
        u'R. Vyčaitė',
        u'R. Ščerbavičius',
        u'Romaldas Navickas',
        u'Rūta',
        u'S. Kareckas',
        u'Sambūris „Patirtis“',
        u'Savivaldybių asociacija',
        u'Savivaldybių asociacija Raseinių rajono savivaldybės administracijos Teisės, personalo ir civilinės metrikacijos skyrius',
        u'Savivaldybių visuomenės sveikatos biurų asociacija',
        u'Simas Zikaras',
        u'Skirmantė Karvelienė',
        u'Smulkių ir vidutinių audito įmonių asociacija',
        u'Soc. mokslų hab. dr. prof. O. Voverienė, Nacionalinės kultūros ir meno premijos laureatas, režisierius, dirigentas P. Mataitis, Joniškio „Aušros“ gimnazijos direktoriaus pavaduotoja V. Bartašienė',
        u'Socialinių inovacijų fondas',
        u'Statybos ir architektūros teismo ekspertų sąjunga',
        u'Susivienijimas Žali.lt, Lietuvos valstiečių ir žaliųjų sąjunga',
        u'Sveikatos mokslų universitetas',
        u'Tarptautinė žmogaus teisių gynimo organizacija „Fair Trials International“',
        u'Lietuvos Respublikos teisėjų asociacija',
        u'Teisės institutas',
        u'Teritorijų detaliojo ir specialiojo planavimo specialistės Agnė enckutė R. Cetkovienė',
        u'Tolerantiško jaunimo Asociacija',
        u'Transparency international Lietuvos skyrius',
        u'UAB Cestos maistas',
        u'UAB Chevron Exploration & Production Lietuva',
        u'UAB Klaipėdos laisvosios ekonominės zonos valdymo bendrovė',
        u'UAB KŪBas',
        u'UAB Urbanistika',
        u'UAB „Aljansas aibė“, kooperatinė bendrovė „Lietuvos kooperatyvų sąjunga“',
        u'UAB „Anuva“',
        u'UAB „Aturis“',
        u"UAB „Bitė Lietuva“, UAB „Tele2', TEO LT, AB",
        u'UAB „Consumeda“',
        u'UAB „Danpower Baltic“',
        u'UAB „Drąseikių karjeras“, UAB „Baltijos karjerai“',
        u'UAB „Grinda“',
        u'UAB „Inspecta“',
        u'UAB „Laboratorinės technologijos“',
        u'UAB „Lietuvos dujų tiekimas“',
        u'UAB „Logotipo projektai“',
        u'UAB „Nacionalinis telekomunikacijų tinklas“',
        u'UAB „Omnitel“, UAB „Bitė Lietuva“ ir UAB „Tele2“',
        u'UAB „Pramonės energija“',
        u'UAB „Saugotyra“',
        u'UAB „Selita“ ir Ko',
        u'UAB „Ūrus“ ir Ko Kauno g. 1A, LT – 01314 Vilnius AB „Palemono keramika“ Pamario g. 1, LT – 52265 Kaunas UAB „Ekovalis“ Ventos g. 8, LT-89103 Mažeikiai UAB „Atliekų tvarkymo centras“ Riovonių g. 2A, LT-03154 Vilnius UAB „Jukneda“ Savanorių pr. 271-311, LT-50131 Kaunas UAB „Geležinkelio detalės“ Kaunakiemio g. 5, LT – 44351 Kaunas UAB „Pabėgis“ Kražantės g. 34, LT – 52109 Kaunas UAB „Aplinkosaugos technologijos“ ir Ko Ringailės g. 10, LT – 47166 Kaunas UAB „Alvinta“ Drobės g. 66, LT – 51369 Kaunas',
        u'V. Čeikuvienė',
        u'V. Žiemelis',
        u'VGTU Miestų statybos katedros pastabos dėl naujo Teritorijų planavimo įstatymo pakeitimo įstatymo projekto',
        u'Valdymo bendrovės, atstovaujančios Kauno, Kėdainių Klaipėdos Marijampolės ir Panevėžio laisvąsias ekonomines zonas',
        u'Valstybinės ne maisto produktų inspekcijos darbuotojų profesinė sąjunga',
        u'Viasat',
        u'Vilniaus Gedimino technikos universitetas',
        u'Vilniaus Senvagės gimnazija',
        u'Vilniaus arkivyskupijos CARITAS',
        u'Vilniaus krašto higienistų ir epidemiologų draugija',
        u'Vilniaus m. Vytenio g. 44 gyventojai',
        u'Vilniaus miesto policijos darbuotojų profesinė sąjunga',
        u'Vilniaus rajono ŽŪB „Vanaginė“',
        u'Vilniaus universiteto Filologijos fakultetas',
        u'Vilniaus universiteto Istorijos fakultetas',
        u'Vilniaus universiteto Komunikacijos fakultetas',
        u'Vilniaus universiteto Medicinos fakultetas',
        u'Vilniaus universiteto Teisės fakultetas',
        u'Vilniaus universiteto Teisės fakulteto profesorius dr. G. Švedas',
        u'Vilniaus universiteto religijos tyrimų studijų centras',
        u'Visuomeninė organizacija „Tėvai prieš narkotikus“',
        u'Vladas Blažys, Skaistrė Andriulienė ir kt. pareigūnai (200 parašų)',
        u'Vytauto Didžiojo universitetas',
        u'VŠĮ CPO LT',
        u'VŠĮ Lietuvos sveikatos mokslų universiteto praktinio mokymo ir bandymų centras',
        u'VŠĮ „Europos parkas“',
        u'VŠĮ „Mokesčių ir verslo procesų administravimo centras“',
        u'VŠĮ „Psichikos sveikatos perspektyvos“(2014.12.11), VŠĮ Žmogaus teisių stebėjimo institutas (2014.12.11), Asociacija „Lietuvos neįgaliųjų forumas“ (2014.12.12), VŠĮ „Paramos vaikams centras“ (2014.12.12), Asociacija „Nacionalinis aktyvių mamų sambūris“ (2014.12.12), Žiburio fondas (2014.12.12), LPF SOS vaikų kaimų Lietuvoje draugija (2014.12.12), VŠĮ Šeimos santykių institutas (2014.12.15), Visuomeninė organizacija „Gelbėkit vaikus“ (2014.12.15)',
        u'VŠĮ „Rūpi“',
        u'VŠĮ „Žaliasis taškas“',
        u'VŠĮ „Žaliasis taškas”, Lietuvos mažų alaus daryklų asociacija, Lietuvos kooperatyvų sąjunga, UAB Aljansas Aibė, Lietuvos pienininkų asociacija, Asociacija „Lietuvos maisto pramonė“, Lietuvos nealkoholinių gėrimų gamintojų bei importuotojų asociacija, Lietuvos natūralaus mineralinio vandens gamintojų asociacija, Lietuvos komunalininkų ir atliekų tvarkytojų asociacija, Baltic Regional WaterCooler Association, G. Valys',
        u'radiminskis@yahoo.com',
        u'Šeimos vaistinių asociacija',
        u'Šiaulių miesto savivaldybės gyventojų asociacija Visuomenės iniciatyvos',
        u'Šiaulių prekybos, pramonės ir amatų rūmai',
        u'Šiaulių valstybinė kolegija',
        u'Švietimo mainų paramos fondas',
        u'Žemės savininkų sąjunga ir Miško savininkų asociacija',
        u'Žemės ūkio bendrovių asociacija',
        u'Žmogaus teisių stebėjimo institutas',
        u'Žuvininkystės ir laivybos tarpšakinės organizacijos l.e.p. Pirmininkas M. Kulakauskas',
        u'Žuvininkystės tarnyba prie ŽŪM',
        u'Žuvininkystės įmonių asociacija „Lampetra“',
        u'Žvejų ir žuvies perdirbėjų asociacija (ŽŽPA) „Baltijos žvejas“',
        u'„Vilnijos“ draugijos pirmininkas hab. dr. K. Garšva',
    ]

    def test_state_actors(self):
        false_negatives = [actor for actor in self.example_state_actors
                           if not is_state_actor(actor)]
        self.assertEqual(false_negatives, [])

    def test_nonstate_actors(self):
        false_positives = [actor for actor in self.example_nonstate_actors
                           if is_state_actor(actor)]
        self.assertEqual(false_positives, [])
