# -*- coding: utf-8 -*-
import unittest

from manoseimas.mps_v2.utils import is_state_actor


class TestStateActorHeuristics(unittest.TestCase):

    example_state_actors = [
        u"(TD)",
        u"Aplinkos ministerija",
        u"ETD prie TM",
        u"Energetikos ministerija",
        u"Europos Teisės departamentas prie LR Teisingumo ministerijos",
        u"Europos Teisės departamentas prie LR teisingumo ministerijos",
        u"Europos Teisės departamentas prie Lietuvos Respublikos Teisingumo ministerijos",
        u"Europos Teisės departamentas prie Lietuvos Respublikos Teisingumo ministerijos, NNNN-",
        u"Europos Teisės departamentas prie Lietuvos Respublikos Teisingumo ministerijos, NNNN-NN",
        u"Europos Teisės departamentas prie Lietuvos Respublikos Teisingumo ministerijos, NNNN-NN-",
        u"Europos Teisės departamentas prie Lietuvos Respublikos teisingumo ministerijos",
        u"Europos Teisės departamentas prie Lietuvos respublikos Teisingumo ministerijos",
        u"Europos Teisės departamentas prie Lietuvos respublikos Teisingumo ministerijos, NNNN-NN-",
        u"Europos Teisės departamentas prie TM",
        u"Europos Teisės departamentas prie Teisingumo ministerijos",
        u"Europos Teisės departamentas",
        u"Europos teisės Departamentas",
        u"Europos teisės departamen-tas prie Lietuvos Respubli-kos teisingumo miniosteri-jos",
        u"Europos teisės departamen-tas prie Lietuvos Respublikos Teisingumo ministerijos",
        u"Europos teisės departamen-tas prie Lietuvos Respublikos teisingumo ministerijos",
        u"Europos teisės departamentas NNNN-NN",
        u"Europos teisės departamentas prie LR TM",
        u"Europos teisės departamentas prie LR Teisingumo ministerijos",
        u"Europos teisės departamentas prie LR teisingumo ministerijos",
        u"Europos teisės departamentas prie Lietuvos Respublikos Teisingumo ministerijos",
        u"Europos teisės departamentas prie Lietuvos Respublikos teisingumo ministerijos NNNN-NN",
        u"Europos teisės departamentas prie Lietuvos Respublikos teisingumo ministerijos",
        u"Europos teisės departamentas prie Lietuvos respublikos teisingumo ministerijos",
        u"Europos teisės departamentas prie R Teisingumo ministerijos",
        u"Europos teisės departamentas prie TM",
        u"Europos teisės departamentas prie Teisingumo ministerijas",
        u"Europos teisės departamentas prie Teisingumo ministerijos (NNNN-NN-NNN",
        u"Europos teisės departamentas prie Teisingumo ministerijos NNNN-",
        u"Europos teisės departamentas prie Teisingumo ministerijos",
        u"Europos teisės departamentas prie Teisingumo ministerijos, NNNN-NN-",
        u"Europos teisės departamentas prie Teisingumo ministerijos, Reg .",
        u"Europos teisės departamentas prie teisingumo ministerijos",
        u"Europos teisės departamentas",
        u"Europos teisės departamentas, prie Teisingumo ministerijos",
        u"Europos teisės departamento prie TM išvada",
        u"Europos teisės departamento prie Teisingumo ministerijos",
        u"Europos teisės depratamentas prie teisingumo ministerijos",
        u"Finansų ministerija",
        u"IVPK",
        u"Informacinės visuomenės plėtros komitetas",
        u"Krašto apsaugos ministerija",
        u"Kultūros ministerija",
        u"Kultūros paveldo departamentas prie Kultūros ministerijos",
        u"Kūno kultūros ir sporto departamentas prie Lietuvos Respublikos Vyriausybės",
        u"Kūno kultūros ir sporto departamentas",
        u"LR Seimo Sveikatos reikalų komiteto neetatinė ekspertė Mykolo Romerio universiteto Politikos mokslų instituto profesorė dr. Danguolė Jankauskienė",
        u"LR Seimo kanceliarijos Teisės departamentas",
        u"LR Specialiųjų tyrimų tarnyba",
        u"LR Sveikatos apsaugos ministerija",
        u"LR Valstybės saugumo departamentas",
        u"LR Vyriausybė",
        u"LR Vyriausybės išvada",
        u"LR Vyriausybės",
        u"LR kultūros ministerija",
        u"LRS Teisės departamentas",
        u"LRS kanceliarijos Teisės departamentas",
        u"LRV išvada",
        u"LRV",
        u"Lietuvos Respub-likos specialiųjų tyrimų tarnyba",
        u"Lietuvos Respubli-kos Vyriausy-bė",
        u"Lietuvos Respublikos Finansų ministerija",
        u"Lietuvos Respublikos Generalinė prokuratūra",
        u"Lietuvos Respublikos Konstitucinis Teismas",
        u"Lietuvos Respublikos Prezidentas",
        u"Lietuvos Respublikos Prezidento dekretas Nr. NK-NNNN",
        u"Lietuvos Respublikos Prezidento kanceliarija",
        u"Lietuvos Respublikos Prezidentės patarėjas Ernestas Rimšelis",
        u"Lietuvos Respublikos Prezidentės",
        u"Lietuvos Respublikos Seimo Teisės ir teisėtvarkos komitetas",
        u"Lietuvos Respublikos Seimo kanceliarijos Teisės departamentas",
        u"Lietuvos Respublikos Seimo narė A. Stancikienė",
        u"Lietuvos Respublikos Specialiųjų tyrimų tarnyba",
        u"Lietuvos Respublikos Valstybės kontrolė",
        u"Lietuvos Respublikos Vyriausybė ( NNNN m. lapkričio NN d. nutarimas Nr. NNNN)",
        u"Lietuvos Respublikos Vyriausybė (NNNN m. birželio NN d. nutarimas Nr. NNN)",
        u"Lietuvos Respublikos Vyriausybė (NNNN m. gegužės NN d. nutarimas Nr. NNN)",
        u"Lietuvos Respublikos Vyriausybė (NNNN m. rugpjūčio NN d. nutarimas Nr. NNN)",
        u"Lietuvos Respublikos Vyriausybė (NNNNm. rugpjūčio NN d. nutarimas Nr. NNN)",
        u"Lietuvos Respublikos Vyriausybė NNNN m. lapkričio NN d. Nr. NNNN",
        u"Lietuvos Respublikos Vyriausybė NNNN.NN.NN. nutarimas Nr. NNN",
        u"Lietuvos Respublikos Vyriausybė",
        u"Lietuvos Respublikos Vyriausybė, (NNNN m. gruodžio N d. nutarimas Nr. NNNN)",
        u"Lietuvos Respublikos Vyriausybė, (Nutarimas Nr. NNNN)",
        u"Lietuvos Respublikos Vyriausybė, NNN N -NN-NN",
        u"Lietuvos Respublikos Vyriausybė, NNNN m. lapkričio NN d. Nr. NNNN",
        u"Lietuvos Respublikos Vyriausybė, NNNN m. rugpjūčio NN d. Nr. NNN",
        u"Lietuvos Respublikos Vyriausybė, nutarimas Nr.NNN",
        u"Lietuvos Respublikos Vyriausybės NNNN m. birželio NN d. išvada Nr. NNN (pastabos, susijusios su įstatymo projektu Nr. XIIP-NNNN)",
        u"Lietuvos Respublikos Vyriausybės NNNN m. birželio NN d. išvada Nr. NNN (pastabos, susijusios su įstatymo projektu Nr. XIP-NNNN(N)) (toliau – LRV)",
        u"Lietuvos Respublikos Vyriausybės NNNN m. birželio NN d. išvada Nr. NNN",
        u"Lietuvos Respublikos Vyriausybės NNNN m. gegužės NN d. išvada Nr. NNN (punktai susiję su įstatymo projektu Nr. XIP-NNNN)",
        u"Lietuvos Respublikos Vyriausybės NNNN m. gegužės NN d. nutarimas Nr. NNN",
        u"Lietuvos Respublikos Vyriausybės NNNN m. liepos NN d. išvada Nr. NNN",
        u"Lietuvos Respublikos Vyriausybės NNNN m. rugpjūčio NN d. išvada Nr. NNN",
        u"Lietuvos Respublikos Vyriausybės nutarimas Nr. NNN",
        u"Lietuvos Respublikos Vyriausybės nutarimas Nr.NNN",
        u"Lietuvos Respublikos Vyriausybės nutarimas",
        u"Lietuvos Respublikos Vyriausybės",
        u"Lietuvos Respublikos aplinkos ministerija",
        u"Lietuvos Respublikos finansų ministerija",
        u"Lietuvos Respublikos konkurencijos taryba",
        u"Lietuvos Respublikos krašto apsaugos ministerija",
        u"Lietuvos Respublikos seimo kanceliarijos Teisės departamentas",
        u"Lietuvos Respublikos specialiųjų tyrimų tarnyba",
        u"Lietuvos Respublikos specialiųjų tyrimų tarnyba, NNNN-NN- raštas Nr. N-NN-NNNN",
        u"Lietuvos Respublikos teisingumo ministerija",
        u"Lietuvos Respublikos užsienio reikalų ministerija",
        u"Lietuvos Respublikos vaiko teisių apsaugos kontrolieriaus įstaiga",
        u"Lietuvos Respublikos valstybės kontrolė",
        u"Lietuvos Respublikos valstybės saugumo departamentas",
        u"Lietuvos Respublikos vidaus reikalų ministerija",
        u"Lietuvos Respublikos vyriausioji rinkimų komisija",
        u"Lietuvos Respublikos ūkio ministerija",
        u"Lietuvos Respublikos žemės ūkio ministerija",
        u"Lietuvos respublikos Vyriausybė",
        u"Muitinės departamentas prie Finansų ministerijos",
        u"Muitinės departamentas prie Lietuvos Respublikos Finansų ministerijos",
        u"Nacionalinė žemės tarnyba prie Žemės ūkio ministerijos",
        u"Narkotikų, tabako ir alkoholio kontrolės departamentas",
        u"Policijos departamentas prie LR VRM",
        u"Policijos departamentas prie VRM",
        u"Policijos departamentas prie Vidaus reikalų ministerijos",
        u"Policijos departamentas",
        u"Prezidentės dekretas, NN N N m. sausio N d. Nr. NK- N NNN",
        u"Priešgaisrinės apsaugos ir gelbėjimo darbų departamentas",
        u"Priešgaisrinės apsaugos ir gelbėjimo departamentas prie Vidaus reikalų ministerijos",
        u"Respublikos Prezidentas",
        u"Respublikos Prezidentė",
        u"S eimo sveikatos reikalų komiteto neetatinė ekspertė dr. Danguolė Jankauskienė",
        u"STT Antikorupcinis vertinimas NNNN-NN",
        u"STT Antikorupcinis vertinimas NNNN-NN-",
        u"STT Antikorupcinis vertinimas",
        u"STT antikorupcinio vertinimo išvada",
        u"STT",
        u"Seimo Antikorupcijos komisija",
        u"Seimo Audito komitetas",
        u"Seimo Biudžeto ir finansų komitetas",
        u"Seimo Informacinės visuomenės plėtros komitetas",
        u"Seimo Kaimo reikalų komitetas",
        u"Seimo Kanceliarijos Teisės departamentas",
        u"Seimo Nacionalinio saugumo ir gynybos komitetas",
        u"Seimo Sveikatos reikalų komitetas",
        u"Seimo Sveikatos reikalų komiteto neetatinė ekspertė doc. dr. A. Širinskienė",
        u"Seimo Sveikatos reikalų neetatinė ekspertė N. Tarvydienė",
        u"Seimo TTK",
        u"Seimo Teisės departamentas",
        u"Seimo Teisės ir teisėtvarkos komitetas",
        u"Seimo Užsienio reikalų komitetas",
        u"Seimo Valstybės valdymo ir savivaldybių komitetas",
        u"Seimo Valstybės valdymo ir savivaldybių komiteto biuro l.e.p. vedėjas A. Astrauskas",
        u"Seimo Valstybės valdymo ir savivaldybių komiteto biuro patarėjas A. Astrauskas",
        u"Seimo biudžeto ir finansų komitetas",
        u"Seimo kance-liarijos Teisės departa-mentas",
        u"Seimo kanceliari- jos Teisės departamen-tas",
        u"Seimo kanceliari-jios Teisės departamentas",
        u"Seimo kanceliari-joas Teisės departa-mentas",
        u"Seimo kanceliari-jos Teisės departa-mentas",
        u"Seimo kanceliari-jos Teisės departa-mentas, NNNN-NN-NNNN",
        u"Seimo kanceliari-jos Teisės departamen-tas",
        u"Seimo kanceliari-jos Teisės departamentas",
        u"Seimo kanceliari-jos teisės departamen-t",
        u"Seimo kanceliari-jos teisės departamen-tas",
        u"Seimo kanceliarijos Teisės d epartamentas",
        u"Seimo kanceliarijos Teisės departamen tas",
        u"Seimo kanceliarijos Teisės departamenats",
        u"Seimo kanceliarijos Teisės departamentas (TD)",
        u"Seimo kanceliarijos Teisės departamentas NNN N -NN- N N",
        u"Seimo kanceliarijos Teisės departamentas NNN N -NN-NN",
        u"Seimo kanceliarijos Teisės departamentas NNNN-NN-NNN",
        u"Seimo kanceliarijos Teisės departamentas",
        u"Seimo kanceliarijos Teisės departamentas, NNN N -NN-NN",
        u"Seimo kanceliarijos Teisės departamentas, NNNN-",
        u"Seimo kanceliarijos Teisės departamento išvada",
        u"Seimo kanceliarijos Teisės depatramentas",
        u"Seimo kanceliarijos Teisės ir teisėtvarkos komiteto patarėja Dalia Latvelienė",
        u"Seimo kanceliarijos teisės departamentas",
        u"Seimo knaceliarijos Teisės departamentas",
        u"Seimo kontrolierių įstaiga",
        u"Seimo narai A. Sysas ir G. Purvaneckienė",
        u"Seimo nariai A. Dumbrava, Š. Birutis, M. Petrauskienė",
        u"Seimo nariai: Antanas Matulas, Vida Marija Čigriejienė",
        u"Seimo narių grupė: E.Masiulis ir kt.",
        u"Seimo narys A.Anušauskas",
        u"Seimo narė A. Pitrėnienė ir kiti Seimo nariai",
        u"Seimo narė Agnė Zuokienė",
        u"Seimo narės R. Šalaševičiūtė, I. Šiaulienė",
        u"Seimo socialinių reikalų ir darbo komitetas",
        u"Seimo teisės ir teisėtvarkos komitetas",
        u"Seimo valstybės valdymo ir savivaldybių komitetas",
        u"Seimo Žmogaus teisių komitetas",
        u"Socialinės apsaugos ir darbo ministerija",
        u"Specialiųjų tyrimo tarnyba",
        u"Specialiųjų tyrimų tarnyba NNNN-NN-... Nr. N-NN...",
        u"Specialiųjų tyrimų tarnyba",
        u"Specialiųjų tyrimų tarnyba, NNNN-",
        u"Specialiųjų tyrimų tarnybos antikorupcinio vertinimo išvada",
        u"Susisiekimo ministerija",
        u"Sveikatos apsaugos ministerija",
        u"Sveikatos reikalų komitetas",
        u"Sveikatos reikalų komiteto pirmininkė Dangutė Mikutienė",
        u"TD",
        u"Teikia: Seimo nariai: Dainius Budrys, Vaidotas Bacevičius, Vytautas Gapšys, Juozas Olekas, Julius Sabatauskas, Erikas Tamašauskas.",
        u"Teisingumo Ministerija",
        u"Teisingumo ministerija",
        u"Teisės departamen-tas prie Lietuvos Respublikos teisingumo ministerijos",
        u"Teisės departamentas",
        u"Vadovybės apsaugos departamentas prie Vidaus reikalų ministerijos",
        u"Valstybinė duomenų apsaugos inspekcija",
        u"Valstybinė kainų energetikos kontrolės komisija",
        u"Valstybinė kainų ir energetikos kontrolės komisija",
        u"Valstybinė kalbos komisija",
        u"Valstybinė kultūros paveldo komisija",
        u"Valstybinė lietuvių kalbos komisija",
        u"Valstybinė lietuvių kalbos komisijos pirmininkė D. Vaišnienė",
        u"Valstybinė maisto ir veterinarijos tarnyba",
        u"Valstybinė mokesčių inspekcija prie FM",
        u"Valstybinė mokesčių inspekcija prie Finansų ministerijos",
        u"Valstybinė mokesčių inspekcija",
        u"Valstybinė teritorijų planavimo ir statybos inspekcija prie Aplinkos ministerijos",
        u"Valstybinės kultūros paveldo komisijos pirmininkė G. Drėmaitė",
        u"Valstybinės saugomų teritorijų tarnyba prie Aplinkos ministerijos Kuršių nerijos nacionalinio parko direkcija",
        u"Valstybės kontrolė",
        u"Valstybės saugumo departamentas",
        u"Valstybės sienos apsaugos tarnyba prie Vidaus reikalų ministerijos",
        u"Valstybės vaiko teisių ir įvaikinimo tarnyba prie socialinės apsaugos ir darbo ministerijos.",
        u"Valstybės valdymo ir savivaldybių komitetas (NNNN-NN-",
        u"Valstybės valdymo ir savivaldybių komitetas",
        u"Vidaus reikalų ministerija",
        u"Viešųjų pirkimų tarnyba",
        u"Vyriausybė",
        u"Vyriausybės atstovo Vilniaus apskrityje tarnyba",
        u"Vyriausybės išvada",
        u"Vyriausybės nutarimas Nr. NNN",
        u"Vyriausybės nutarimas Nr.NNN",
        u"Vyriausybės",
        u"Švietimo ir mokslo ministerija",
        u"Žemės ūkio ministerija",
        u"Audito komitetas NNNN-NN-",
        u"Kaimo reikalų komitetas",
        u"Lietuvos bioetikos komitetas",
        u"Nacionalinio saugumo ir gynybos komitetas",
        u"Socialinių reikalų ir darbo komitetas",
        u"Socialinių reikalų ir darbo komiteto išvada",
        u"TTK biuro patarėja Rita Karpavičiūtė",
        u"Teisės ir teisėtvarkos komitetas",
        u"Teisės ir teisėtvarkos komiteto NNNN m. kovo NN d. išvada dėl galimo prieštaravimo Konstitucijai (Seimo kanceliarijos Teisės departamento pastaba Nr. N)",
        u"Teisės ir teisėtvarkos komiteto biuro patarėja Irma Leonavičiūtė",
        u"Teisės ir teisėtvarkos komiteto biuro patarėja L.Zdanavičienė",
        u"Teisės ir teisėtvarkos komiteto biuro patarėja Loreta Zdanavičienė",
        u"Teisės ir teisėtvarkos komiteto biuro patarėja M. Civilkienė",
        u"Teisės ir teisėtvarkos komiteto biuro patarėja M.Civilkienė",
        u"Teisės ir teisėtvarkos komiteto biuro patarėja Rita Varanauskienė",
        u"Teisės ir teisėtvarkos komiteto išvada",
        u"Teisės ir teisėtvarkos komiteto patarėja M.Civilkienė",
        u"Teisės ir teisėtvarkos komiteto patarėja R. Karpavičiūtė",
        u"Užsienio reikalų komitetas",
        u"Švietimo, mokslo ir kultūros komitetas",
        u"Žmogaus teisių komitetas",
        u"Žmogaus teisių komitetas, NNN N -NN-NN",
        u'Aplinkos apsaugos komitetas',
        u'Audito komitetas',
        u'BFK',
        u'Biudžeto ir finansų komitetas',
        u'Ekonomikos komitetas',
        u'Europos reikalų komitetas',
    ]

    # TODO: decide if these are supposed to be state or non-state actors
    # and move them to the right list of examples
    undecided = [
        u"Alytaus m. savivaldybės meras J. Krasnickas",
        u"Alytaus regiono plėtros taryba",
        u"Biržų rajono savivaldybės merė",
        u"Etninės kultūros globos tarybos pirmininkė D. Urbanavičienė",
        u"Generalinė prokuratūra",
        u"Ignalinos atominės elektrinės regiono plėtros taryba",
        u"Jonavos rajono savivaldybė",
        u"Joniškio r. Savivaldybės meras Gediminas Čepulis",
        u"Jungtinių Tautų Vyriausiojo pabėgėlių komisaro atstovas Lietuvoje",
        u"Kalvarijos savivaldybės meras",
        u"Kauno miesto savivaldybės administracija",
        u"Kauno miesto savivaldybės meras",
        u"Klaipėdos miesto savivaldybės meras",
        u"Klaipėdos rajono savivaldybės meras",
        u"Konkurencijos taryba",
        u"LR Generalinė prokuratūra",
        u"LR Vaiko teisių apsaugos kontrolierė Edita Žiobienė",
        u"LR valstybinės kultūros paveldo komisijos pirmininkė G. Drėmaitė",
        u"Lietuvos Aukščiausiasis Teismas",
        u"Lietuvos Aukščiausiasis teismas",
        u"Lietuvos Kelių policijos tarnyba",
        u"Lietuvos Respublikos Trišalė taryba",
        u"Lietuvos Respublikos Trišalės tarybos pirmininkas Artūras Černiauskas",
        u"Lietuvos Respublikos Trišalės tarybos posėdis",
        u"Lietuvos Respublikos trišalės tarybos Kultūros komiteto pirmininkas P. Zurlys",
        u"Lietuvos Respublikos žemės ūkio rūmai",
        u"Lietuvos Savivaldybių asociacija",
        u"Lietuvos advokatūra",
        u"Lietuvos antstolių rūmai",
        u"Lietuvos apeliacinis teismas",
        u"Lietuvos bankas",
        u"Lietuvos banko priežiūros tarnyba",
        u"Lietuvos centrinė kredito unija",
        u"Lietuvos kelių policijos tarnyba",
        u"Lietuvos nacionalinis radijas ir televizija",
        u"Lietuvos savivaldybių seniūnų asociacija",
        u"Lietuvos smulkiojo ir vidutinio verslo taryba",
        u"Lietuvos trišalė taryba",
        u"Lietuvos valstybės tarnautojų, biudžetinių ir viešųjų įstaigų darbuotojų profesinės sąjungos pirmininkė Irena Petraitienė, Slaugos ir socialinių darbuotojų profesinės sąjungos „Solidarumas“ pirmininkė Jurgita Žiūkienė, Lietuvos socialinių įstaigų darbuotojų profesinės sąjungos pirmininkas Egidijus Vičiūnas, Lietuvos socialines paslaugas teikiančių darbuotojų profesinės sąjungos pirmininkė Vida Gricienė",
        u"Lietuvos valstybės tarnautojų. biudžetinių ir viešųjų įstaigų darbuotojų profesinė sąjungą Slaugos ir socialinių darbuotojų profesinė sąjunga „Solidarumas\" Lietuvos socialinių Įstaigų darbuotojų profesinė sąjunga Lietuvos socialines paslaugas teikiančių darbuotojų profesinė sąjungą",
        u"Lošimų priežiūros tarnyba",
        u"Lygių galimybių kontrolie- riaus tarnyba",
        u"Lygių galimybių kontrolieriaus tarnyba",
        u"LŽŪBA",
        u"Marijampolės regiono plėtros taryba",
        u"Marijampolės savivaldybės meras",
        u"Mažeikių r. savivaldybės administracijos direktorius Bronius Kryžius",
        u"Mažeikių rajono savivaldybės meras Antanas Tenys",
        u"NSGK",
        u"Nacionalinis transplantacijos biuras",
        u"Nacionalinė nevyriausybinių organizacijų platforma",
        u"Nacionalinė sveikatos taryba",
        u"Nacionalinė tabako ir alkoholio kontrolės koalicija",
        u"Nacionalinė teismų administracija",
        u"Nacionalinės sveikatos tarybos sekretoriatas",
        u"Neringos savivaldybė",
        u"Neringos savivaldybės administracija",
        u"Neringos savivaldybės meras",
        u"Neįgaliųjų reikalų tarybos prie Socialinės apsaugos ir darbo ministerijos pirmininkas Algirdas Šešelgis",
        u"Pikelių miestelio bendruomenės pirmininkė Gražina Elena Juknevičienė",
        u"Respublikiniai būsto valdymo ir priežiūros rūmai",
        u"Respublikos rajono savivaldybių priešgaisrinių tarnybų vadovai",
        u"Savivaldybių asociacija",
        u"Seimo Vystomojo bendradarbiavimo, reprodukcinės sveikatos ir teisių parlamentinė grupė, Šeimos planavimo ir seksualinės sveikatos asociacija, Lietuvos medicinos studentų asociacija, Moterų informacijos centras, Lygių galimybių plėtros centras, Lietuvos moterų lobistinė organizacija, Kauno moters užimtumo ir informacijos centras, Žmogaus teisių stebėjimo institutas, Žmogaus teisių centras, Marijampolės moters veiklos centras, VŠĮ „Įvairovės ir edukacijos namai“, Lietuvos etninių grupių moterų verslininkių draugija, Lietuvos estų draugija, Tolerantiško jaunimo asociacija, NVO „Branda“, ŽIV ir AIDS paveiktų moterų bei jų artimųjų asociacija, Anykščių moterų užimtumo ir informacijos centras, Nacionalinis socialinės integracijos institutas, Marijampolės apskrities moterų namai - krizių centras",
        u"Teisėjų taryba",
        u"Teritorijų detaliojo ir specialiojo planavimo specialistė E.Urbonavičiūtė Teritorijų specialiojo planavimo specialistas R.Markus",
        u"Teritorijų detaliojo ir specialiojo planavimo specialistės A.Venckutė, R.Cvetkovienė",
        u"Vaiko teisių apsaugos kontrolie - riaus įstaiga",
        u"Vaiko teisių apsaugos kontrolieriaus tarnyba",
        u"Vaiko teisių apsaugos kontrolieriaus įstaiga",
        u"Vaiko teisių apsaugos kontrolieriaus įstaiga.",
        u"Vaiko teisių apsaugos kontrolierius",
        u"Vaiko teisių apsaugos kontrolierė",
        u"Valstybinis patologijos centras",
        u"Valstybės įmonė „Registrų centras“",
        u"Vilniaus m. savivaldybės meras A.Zuokas",
        u"Vilniaus miesto savivaldy-bės administra-cija",
        u"Vilniaus miesto savivaldybė (Nr. G-NNNN-NNNN)",
        u"Vilniaus miesto savivaldybė",
        u"Vilniaus miesto savivaldybės meras",
        u"Vyriausiasis administracinis teismas",
        u"Vyriausioji administracinių ginčų komisija",
        u"Vyriausioji tarnybinės etikos komisija",
        u"Švietimo mainų paramos fondas",
        u"Ūkio ministerija",
        u"Žemės ūkio rūmai",
        u"ŽŪR",
        u'Etninės kultūros globos taryba',
        u'Europos Centrinio banko nuomonė',
        u'Europos Centrinis Bankas',
        u'Europos Parlamento narys P. Auštrevičius',
        u'Europos centrinis bankas',
    ]

    example_nonstate_actors = [
        u",,Linava“",
        u"AB LESTO",
        u"AB Litgrid",
        u"AB „Amber grid“",
        u"AB „Lesto“",
        u"AB „Lietuvos dujos“",
        u"Adolfas Norkūnas",
        u"Agnė Širinskienė",
        u"Agrarinės ekonomikos institutas",
        u"Anoniminis",
        u"Asociacija ,,Infobalt“",
        u"Asociacija „ Investors' Forum”",
        u"Asociacija „INFOBALT“",
        u"Asociacija „Infobalt“",
        u"Asociacija „Investuotojų forumas“",
        u"Asociacija „Kultūros savivaldos kolegija“",
        u"Asociacija „Lietuvos antstolių rūmai“",
        u"Asociacija „Lietuvos keliai“",
        u"Asociacija „Lietuvos kreditas“",
        u"Asociacija „Lietuvos maisto pramonė“",
        u"Asociacijos „Šnieriškių bendruomenė“ pirmininkas Sergejus Jeriomenko (Šnieriškių k., Molėtų raj.)",
        u"Ateitininkų medikų korporacija ,,Gaja“",
        u"Baltijos pluoštinių kultūrų augintojų ir perdirbėjų asociacija",
        u"Biodegalų asociacija",
        u"Dalios Zeleckienės advokatų kontora",
        u"Dr. Antanas Mitašiūnas, LR elektroninio parašo įstatymo, priimto LR Seime NNNN m. liepos NN d., projekto autorius",
        u"E. Rimgaila ir NNNN piliečių parašų",
        u"Ekspertas doc. Aurelijus Veryga",
        u"Gausių šeimų asociacija",
        u"Investuotojų asociacija",
        u"Investuotojų forumas",
        u"Kauno kolegijos direktorius Mindaugas Misiūnas",
        u"Kauno l/d „Varpelis“ direktorė L. Kasiulynienė",
        u"Klaipėdos miesto ir apskrities profesinė sąjunga",
        u"LITDEA",
        u"LNVAA „Linava”",
        u"Laisvos visuomenės institutas",
        u"Laisvosios rinkos institutas",
        u"Legalaus verslo aljansas",
        u"Lietuviškų degalinių sąjunga",
        u"Lietuvos Nepriklauso-mybės Akto signataras Zigmas Vaišvila",
        u"Lietuvos Respublikiniai būsto valdymo ir priežiūros rūmai",
        u"Lietuvos Respublikos namų ir žemės sklypų savininkų sąjunga",
        u"Lietuvos Respublikos transporto priemonių draudikų biuras",
        u"Lietuvos Sąjūdžio Vilniaus miesto taryba",
        u"Lietuvos Sąjūdžio Vilniaus skyriaus taryba",
        u"Lietuvos Teisės institutas",
        u"Lietuvos Teisėsaugos pareigūnų federacija",
        u"Lietuvos apskaitos įmonių asociacija",
        u"Lietuvos architektų rūmai",
        u"Lietuvos asociacija „Gyvastis“",
        u"Lietuvos bankų asociacija",
        u"Lietuvos didžiųjų miestų merų forumas",
        u"Lietuvos jaunimo organizacijų taryba",
        u"Lietuvos kaimo bendruomenių sąjunga",
        u"Lietuvos karjerų asociacija",
        u"Lietuvos laisvosios rinkos institutas",
        u"Lietuvos mokslų akademija",
        u"Lietuvos mokytojų profesinė sąjunga",
        u"Lietuvos nacionalinė filharmonija",
        u"Lietuvos nacionalinė vartotojų federacija",
        u"Lietuvos notarų rūmai",
        u"Lietuvos radijo ir televizijos asociacija",
        u"Lietuvos radijo ir televizijos komisija",
        u"Lietuvos tautinis olimpinis komitetas",
        u"Lietuvos techninės apžiūros įmonių asociacija",
        u"Lietuvos valstybinis simfoninis orkestro meno vadovas G. Rinkevičius",
        u"Lietuvos vyskupų konferencija",
        u"Lietuvos žmogaus teisių asociacija",
        u"Lietuvos žmogaus teisių centras",
        u"Lietuvos žmogaus teisių gynimo asociacija",
        u"NVO tinklas „Regina“",
        u"Nacionalinis pareigūnų profesinių sąjungų susivienijimas",
        u"Nacionalinė turizmo verslo asociacija",
        u"Nacionalinė vaistų prekybos asociacija",
        u"O. Batkienė",
        u"OHLB “Kraujas”",
        u"Ortopedijos ir reabilitacijos paslaugų teikėjų asociacija",
        u"Padvarnių kaimo bendruomenė",
        u"Pagalbos onkologiniams ligoniams asociacija",
        u"Pil. Antanas Vasiliauskas pareiškimas reg. Nr. g-NNNN-NNN",
        u"Pilietis, Justinas Gudonis",
        u"Pilietė Dalia Cironkaitė",
        u"Piliečio pasiūlymas",
        u"Piliečių gynybos paramos fondas",
        u"Prof. Algimantas Kirkutis Lietuvos sveikos gyvensenos ir natūraliosios medicinos rūmų Prezidentas",
        u"Profesinė sąjunga „Uostininkas“",
        u"Respublikinė Šiaulių ligoninė",
        u"Teisės institutas",
        u"Transparency International Lietuvos skyrius (toliau – TILS)",
        u"UAB KŪBas",
        u"UAB “Kūbas“",
        u"UAB „Aturis“",
        u"Ugniagesys Juozas Alaburda",
        u"Uždaroji akcinė bendrovė „Vilniaus viešasis transportas“",
        u"Užkrečiamųjų ligų ir AIDS centras",
        u"Vaiko teisių apsaugos tarnybų (skyrių) vadovų asociacija",
        u"Viasat A.S.",
        u"Viasat",
        u"Vida Jakiūnaitė",
        u"Vilniaus Gedimino technikos universitetas",
        u"Vilniaus krašto higienistų ir epidemiologų draugija",
        u"Vilniaus m. Vytenio g. 42 gyventojai",
        u"Vilniaus miesto savivaldybės Lazdynų poliklinika",
        u"Vilniaus universiteto Teisės fakultetas",
        u"Visuomeninė organizacija „Tėvai prieš narkotikus“",
        u"VšĮ Ignalinos atominės elektrinės regiono plėtros agentūra",
        u"VšĮ Lietuvos laisvosios rinkos institutas",
        u"VšĮ Lietuvos nacionalinis radijas ir televizija Administravimo ir veiklos vystymo departamento vadovė A. Kružikienė",
        u"VšĮ „Lietuvos nacionalinis radijas ir televizija“",
        u"vida.jakiunaite",
        u"Šeimos planavimo ir seksualinės sveikatos asociacija",
        u"Žemės ūkio bendrovių asociacija",
        u"Žmogaus teisių stebėjimo institutas",
        u"Žuvininkystės įmonių asociacija „Lampetra“",
    ]

    def test_state_actors(self):
        false_negatives = [actor for actor in self.example_state_actors
                           if not is_state_actor(actor)]
        self.assertEqual(false_negatives, [])

    def test_nonstate_actors(self):
        false_positives = [actor for actor in self.example_nonstate_actors
                           if is_state_actor(actor)]
        self.assertEqual(false_positives, [])
