Vagrant.require_version ">= 1.6"

Vagrant.configure('2') do |config|
  config.vm.define 'box' do |box|
    box.vm.box = 'ubuntu/trusty64'
    box.vm.network :forwarded_port, guest: 80, host: 8080
    box.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy.yml"
      ansible.extra_vars = {
        vars: "vagrant",
      }
    end
  end
  config.vm.provider "virtualbox" do |v|
    # lxml does not compile with 512
    v.memory = 1024
  end
end
